// Pure capability-broker logic — envelope construction, scoping decisions, and
// the M1 in-process `ping` no-op resolver. This module MUST stay free of any
// `electron` import so it can be unit-tested under Vitest's node environment.
// The IPC wiring that calls into these functions lives in
// `frontendPluginManager.ts`.

import { eventNamespace, resolveWsType } from './capabilityMap'
import {
  HOST_SHELL_EXECUTABLE_ALLOWLIST,
  publicCapabilityEntry,
  storageRequestValidationError,
  type PublicCapabilityScope,
  type StoragePartitionClass,
} from './pluginCapabilityCatalog'
import type { PluginShellMode, PluginSystemNamespace } from './pluginManifestV2'
import type { PluginCapabilityPolicy } from './pluginPermissions'
import type { WsResponse } from '../../shared/wsClient'
import type { ExecutionPolicySnapshot } from './executionPolicy'

/** A capability call as it arrives from a plugin view over IPC. */
export interface CapabilityCall {
  /** The manifest id of the calling plugin (injected by the manager, not the view). */
  pluginId: string
  /** Capability namespace, e.g. `ping`, `fs`, `git`. */
  ns: string
  /** Method within the namespace. */
  method: string
  /** Opaque, plugin-supplied arguments. */
  args: unknown
  /** Correlation id generated by the plugin preload. */
  reqId: string
}

/** The response envelope returned to the plugin view. */
export interface CapabilityResponse {
  reqId: string
  ok: boolean
  result?: unknown
  error?: { code: CapabilityErrorCode; message?: string }
}

export type CapabilityErrorCode =
  | 'CAP_DENIED'
  | 'UNKNOWN'
  | 'BAD_REQUEST'
  | 'BACKEND_ERROR'
  | 'RESOURCE_LIMIT'
  | 'CAPABILITY_DENIED'
  | 'METHOD_NOT_FOUND'
  | 'INVALID_ARGUMENT'
  | 'WORKSPACE_SCOPE_VIOLATION'
  | 'USER_CANCELLED'
  | 'TIMEOUT'
  | 'BACKEND_UNAVAILABLE'
  | 'PLUGIN_STOPPING'
  | 'CREDENTIAL_REQUIRED'
  | 'STORAGE_QUOTA_EXCEEDED'
  | 'INTERNAL_ERROR'

export interface AuthenticatedRuntimeBinding {
  pluginId: string
  packageVersion: string
  workspaceId: string | null
  instanceId: string | null
  audience: string | null
}

export interface HostCapabilityGrant {
  packageVersion: string
  system: readonly PluginSystemNamespace[]
  shell?: PluginShellMode
  highRiskShellConfirmed?: boolean
  /** Host-managed storage grant. Not declared in a Manifest: the Host decides
   *  which packages may read/write their partition. */
  storage?: boolean
}

export interface HostCapabilityContext {
  /** Eligibility is an install/Host fact, never a grant. */
  publisherEligible: boolean
  /** The user-approved package-version grant, or null before approval. */
  userGrant: HostCapabilityGrant | null
  /** Host-authenticated identity; never read from a plugin request. */
  runtimeBinding: AuthenticatedRuntimeBinding | null
  /** Host-configured AI CLI profile ids; the Plugin cannot define profiles. */
  aiCliProfiles?: readonly string[]
  /** Host-owned AI CLI session bindings, keyed by opaque session id. */
  sessionBindings?: ReadonlyMap<string, AuthenticatedRuntimeBinding>
  /** Host-owned pending start bindings, keyed by opaque request id. */
  pendingStartBindings?: ReadonlyMap<string, AuthenticatedRuntimeBinding>
  /** Package versions bound to each versioned storage snapshot, keyed by
   *  snapshot tier. Lets a storage call select only the snapshot whose package
   *  version matches the binding's — no other selection is permitted. */
  storageSnapshots?: ReadonlyMap<StorageSnapshotTier, string>
  /** Host-selected tier fixed for the lifetime of one runtime instance. */
  storageSnapshotTier?: StorageSnapshotTier
  /** Host-authenticated operation origin. Plugin payloads never provide this. */
  initiator?: AuthenticatedInitiator
  /** Effective agent policy captured when this operation was admitted. */
  executionPolicy?: ExecutionPolicySnapshot
}

/** Host-authenticated origin of an operation. This is an internal value: it is
 * never accepted from a Plugin request or exposed through the preload API. */
export type AuthenticatedInitiator =
  | Readonly<{ kind: 'user'; id: string }>
  | Readonly<{ kind: 'agent'; source: 'mcp'; id: string }>

/** Stable Host identity used for direct user work when no account identity is
 * available at this internal boundary. It is not a credential. */
export const HOST_USER_INITIATOR: AuthenticatedInitiator = Object.freeze({
  kind: 'user',
  id: 'host-user',
})

/** Validate an initiator at a Host boundary before it is attached to work. */
export function isAuthenticatedInitiator(value: unknown): value is AuthenticatedInitiator {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false
  const record = value as Record<string, unknown>
  if (record.kind === 'user') {
    return (
      Object.keys(record).length === 2 &&
      Object.keys(record).every((key) => key === 'kind' || key === 'id') &&
      typeof record.id === 'string' &&
      record.id.length > 0
    )
  }
  return (
    record.kind === 'agent' &&
    Object.keys(record).length === 3 &&
    Object.keys(record).every((key) => key === 'kind' || key === 'source' || key === 'id') &&
    record.source === 'mcp' &&
    typeof record.id === 'string' &&
    record.id.length > 0
  )
}

/** A tier name for the Host-managed versioned storage snapshots. */
export type StorageSnapshotTier = 'candidate' | 'active' | 'previous'

/** The Host-derived partition a storage call may read/write. The Plugin never
 *  selects any field here — `pluginId` and (for workspace scope) `workspaceId`
 *  come from the authenticated runtime binding, and `key` is the only value the
 *  Plugin supplies. */
export interface StoragePartition {
  pluginId: string
  workspaceId: string | null
  key: string
}

/** Which versioned storage snapshot a plan targets, matched to the package
 *  version it is bound to. */
export interface StorageSnapshotRef {
  pluginId: string
  tier: StorageSnapshotTier
  packageVersion: string
}

/** A Host-managed storage plan. Besides the partition identity it carries the
 *  selected snapshot tier so a plugin can never read or write a snapshot that
 *  does not match its own package version. */
export interface StoragePlan {
  partition: StoragePartition
  snapshot: StorageSnapshotRef
}

export interface PublicCapabilityExecutionPlan {
  kind: 'public'
  address: string
  scope: PublicCapabilityScope
  args: Record<string, unknown>
  runtime: AuthenticatedRuntimeBinding
  /** Host-authenticated origin retained for downstream adapters. */
  initiator?: AuthenticatedInitiator
  /** Policy revision captured when this plan was admitted. */
  policyRevision?: number
  shellMode?: PluginShellMode
  session?: AuthenticatedRuntimeBinding
  storage?: StoragePlan
}

export type PublicCapabilityDecision =
  | { kind: 'allow'; plan: PublicCapabilityExecutionPlan }
  | { kind: 'deny'; response: CapabilityResponse }

/**
 * Namespaces the host grants without an explicit `requires` declaration. `ping`
 * is the M1 built-in used to prove the IPC envelope round-trips end to end.
 */
export const BUILTIN_CAPABILITIES: readonly string[] = ['ping']

/** Reserved source identity used by Host-produced workspace events. */
export const HOST_EVENT_SOURCE_PLUGIN_ID = 'host'

/**
 * Scoping decision: may a plugin whose manifest declares `requires` call `ns`?
 * Built-in namespaces (see {@link BUILTIN_CAPABILITIES}) are always allowed;
 * everything else must be listed in the plugin's `requires`.
 */
export function isCapabilityAllowed(requires: readonly string[], ns: string): boolean {
  if (BUILTIN_CAPABILITIES.includes(ns)) return true
  return requires.includes(ns)
}

export type CapabilityPolicyInput = PluginCapabilityPolicy | readonly string[]

function isRequirementsArray(policy: CapabilityPolicyInput): policy is readonly string[] {
  return Array.isArray(policy)
}

function isLegacyPolicy(
  policy: CapabilityPolicyInput
): policy is { kind: 'legacy'; requires: readonly string[] } {
  return !isRequirementsArray(policy) && (policy as PluginCapabilityPolicy).kind === 'legacy'
}

function isManifestV2Policy(
  policy: CapabilityPolicyInput
): policy is Extract<PluginCapabilityPolicy, { kind: 'manifest-v2' }> {
  return !isRequirementsArray(policy) && (policy as PluginCapabilityPolicy).kind === 'manifest-v2'
}

/** Check the namespace projection for legacy callers and coarse v2 policy
 *  inspection. Actual v2 execution still requires Host authorization context. */
export function isCallAllowed(
  policy: CapabilityPolicyInput,
  ns: string,
  method: string
): boolean {
  if (isRequirementsArray(policy)) return isCapabilityAllowed(policy, ns)
  if (isLegacyPolicy(policy)) return isCapabilityAllowed(policy.requires, ns)
  if (BUILTIN_CAPABILITIES.includes(ns)) return true
  const v2 = policy
  void method
  return v2.system.includes(ns as PluginSystemNamespace) || (ns === 'shell' && v2.shell !== undefined)
}

/** V2 events require the authenticated Host binding and therefore cannot use
 * this legacy declaration-only helper. Callers must use
 * {@link isPublicCapabilityEventAllowed} with Host context. */
export function isEventAllowed(policy: CapabilityPolicyInput, event: string): boolean {
  if (isManifestV2Policy(policy)) {
    void event
    return false
  }
  const ns = eventNamespace(event)
  if (!ns) return false
  if (isRequirementsArray(policy)) return isCapabilityAllowed(policy, ns)
  if (isLegacyPolicy(policy)) return isCapabilityAllowed(policy.requires, ns)
  return false
}

/** Build a success envelope. */
export function buildSuccess(reqId: string, result: unknown): CapabilityResponse {
  return { reqId, ok: true, result }
}

/** Build an error envelope. */
export function buildError(
  reqId: string,
  code: CapabilityErrorCode,
  message?: string
): CapabilityResponse {
  return { reqId, ok: false, error: message ? { code, message } : { code } }
}

/**
 * Validate an untrusted IPC payload into a {@link CapabilityCall}. Returns
 * `null` when the shape is wrong so the caller can reject with `BAD_REQUEST`.
 * `pluginId` is authoritative from the manager, so it is not read from the
 * payload here — the caller supplies it.
 */
export function parseCapabilityCall(raw: unknown, pluginId: string): CapabilityCall | null {
  if (typeof raw !== 'object' || raw === null) return null
  const r = raw as Record<string, unknown>
  if (typeof r.ns !== 'string' || r.ns.length === 0) return null
  if (typeof r.method !== 'string' || r.method.length === 0) return null
  if (typeof r.reqId !== 'string' || r.reqId.length === 0) return null
  return { pluginId, ns: r.ns, method: r.method, args: r.args, reqId: r.reqId }
}

/**
 * Resolve a capability call to its response, given the calling plugin's
 * declared `requires`. This is the whole M1 broker surface:
 *   - not allowed        → `CAP_DENIED`
 *   - `ping`/any method  → `{ pong: true, echo: args }`
 *   - anything else       → `UNKNOWN`
 * M2 replaces the `ping` branch with a dispatch to the backend WS host.
 */
export function resolveCapabilityCall(
  call: CapabilityCall,
  requires: readonly string[]
): CapabilityResponse {
  if (!isCapabilityAllowed(requires, call.ns)) {
    return buildError(call.reqId, 'CAP_DENIED', `capability '${call.ns}' not granted`)
  }
  if (call.ns === 'ping') {
    return buildSuccess(call.reqId, { pong: true, echo: call.args })
  }
  return buildError(call.reqId, 'UNKNOWN', `no handler for '${call.ns}.${call.method}'`)
}

/**
 * Host-implemented capabilities: `(ns.method)` calls the manager services in
 * the main process itself instead of dispatching to the backend WS. Scoping
 * still applies (the ns must be granted by the manifest). `open_in_editor`
 * routes a file to the mini-IDE plugin window — with the main-side
 * openMiniIdeEditor fallback chain (OS default app when the mini-IDE is not
 * installed/available).
 */
export const HOST_CAPABILITIES: Readonly<Record<string, string>> = {
  'ui.open_in_editor': 'open_in_editor',
  // Shell-level actions the Git window's worktree/remote cards need (GitPane
  // parity): open an http(s) URL in the default browser, reveal a path in the
  // OS file manager, open a workspace in a new main window, and a native
  // directory picker (async result).
  'ui.open_external': 'open_external',
  'ui.reveal_path': 'reveal_path',
  'ui.open_workspace': 'open_workspace',
  'ui.pick_folder': 'pick_folder',
}

function publicDenied(reqId: string, code: CapabilityErrorCode, message: string): PublicCapabilityDecision {
  return { kind: 'deny', response: buildError(reqId, code, message) }
}

function sameBinding(
  left: AuthenticatedRuntimeBinding,
  right: AuthenticatedRuntimeBinding
): boolean {
  return (
    left.pluginId === right.pluginId &&
    left.packageVersion === right.packageVersion &&
    left.workspaceId === right.workspaceId &&
    left.instanceId === right.instanceId &&
    left.audience === right.audience
  )
}

function publicRequestArgs(call: CapabilityCall): Record<string, unknown> | null {
  return typeof call.args === 'object' && call.args !== null && !Array.isArray(call.args)
    ? { ...(call.args as Record<string, unknown>) }
    : null
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/** Return the executable token at the start of every shell pipeline/chain segment.
 * This is intentionally a lexical check: the Host never executes or expands the
 * command while deciding whether it is allowlisted. Version 1 does not inspect
 * subcommands or arguments. */
export function shellTopLevelExecutables(command: string): string[] | null {
  if (command.trim().length === 0) return null
  const segments: string[] = []
  let segmentStart = 0
  let quote: 'single' | 'double' | null = null
  let escaped = false

  const pushSegment = (end: number): boolean => {
    const segment = command.slice(segmentStart, end).trim()
    if (!segment) return false
    segments.push(segment)
    return true
  }

  for (let index = 0; index < command.length; index += 1) {
    const char = command[index]
    if (escaped) {
      escaped = false
      continue
    }
    if (char === '\\' && quote !== 'single') {
      escaped = true
      continue
    }
    if (quote === 'single') {
      if (char === "'") quote = null
      continue
    }
    if (quote === 'double') {
      if (char === '`' || (char === '$' && command[index + 1] === '(')) return null
      if (char === '"') quote = null
      continue
    }
    if (
      char === '`' ||
      (char === '$' && command[index + 1] === '(') ||
      char === '<' ||
      char === '>' ||
      char === '(' ||
      char === ')' ||
      char === '{' ||
      char === '}' ||
      char === '!'
    ) {
      return null
    }
    if (char === "'") {
      quote = 'single'
      continue
    }
    if (char === '"') {
      quote = 'double'
      continue
    }
    if (char === '|' && command[index + 1] === '&') {
      if (!pushSegment(index)) return null
      index += 1
      segmentStart = index + 1
      continue
    }
    if (char === ';' || char === '|' || char === '&' || char === '\n' || char === '\r') {
      if (!pushSegment(index)) return null
      if ((char === '|' || char === '&') && command[index + 1] === char) index += 1
      segmentStart = index + 1
    }
  }
  if (quote !== null || escaped || !pushSegment(command.length)) return null

  const executables: string[] = []
  for (const segment of segments) {
    let index = 0
    while (/\s/.test(segment[index] ?? '')) index += 1
    if (index === segment.length) return null
    let token = ''
    let tokenQuote: 'single' | 'double' | null = null
    let tokenEscaped = false
    for (; index < segment.length; index += 1) {
      const char = segment[index]
      if (tokenEscaped) {
        token += char
        tokenEscaped = false
        continue
      }
      if (char === '\\' && tokenQuote !== 'single') {
        tokenEscaped = true
        continue
      }
      if (tokenQuote === 'single') {
        if (char === "'") tokenQuote = null
        else token += char
        continue
      }
      if (tokenQuote === 'double') {
        if (char === '"') tokenQuote = null
        else token += char
        continue
      }
      if (char === "'") {
        tokenQuote = 'single'
        continue
      }
      if (char === '"') {
        tokenQuote = 'double'
        continue
      }
      if (/\s/.test(char)) break
      token += char
    }
    if (!token || tokenQuote !== null || tokenEscaped) return null
    // A leading assignment changes the environment of the command that
    // follows it. Version 1 does not resolve shell prefixes, so do not let a
    // denylist inspect the assignment token and miss the real executable.
    if (/^[A-Za-z_][A-Za-z0-9_]*=/u.test(token)) return null
    // A path-qualified token is not reduced to a basename: doing so would let
    // a Plugin replace an allowlisted command with an arbitrary same-named
    // executable from the workspace or a temporary directory.
    if (token.includes('/') || token.includes('\\')) return null
    executables.push(token.trim())
  }
  return executables.every((value) => value.length > 0) ? executables : null
}

function shellCommandAllowed(command: string, allowlist: readonly string[]): boolean {
  const executables = shellTopLevelExecutables(command)
  return executables !== null && executables.every((executable) => allowlist.includes(executable))
}

/** Decide the agent-only Execution Policy filter for one first-level public
 * namespace or shell command. Manifest, Grant, catalog, and runtime checks are
 * intentionally outside this function and remain mandatory for every caller. */
export function executionPolicyAllows(
  initiator: AuthenticatedInitiator | undefined,
  snapshot: ExecutionPolicySnapshot | undefined,
  namespace: PluginSystemNamespace | 'shell',
  command?: string,
): boolean {
  // Direct user work is governed by the existing Host checks, not by the
  // agent-oriented Execution Policy. An omitted initiator preserves legacy
  // direct-user behavior for callers that predate this seam.
  if (!initiator || initiator.kind !== 'agent') return true
  if (!snapshot || snapshot.state === 'corrupt') return false

  const { policy } = snapshot
  if (policy.mode === 'full') return true
  if (namespace === 'shell') {
    const executables = shellTopLevelExecutables(command ?? '')
    if (!executables) return false
    // Policy entries are persisted in lowercase; normalize command tokens at
    // the enforcement boundary so case-insensitive filesystems cannot bypass policy.
    const canonicalExecutables = executables.map((executable) => executable.toLowerCase())
    return policy.mode === 'allowlist'
      ? canonicalExecutables.every((executable) => policy.shell.includes(executable))
      : canonicalExecutables.every((executable) => !policy.shell.includes(executable))
  }
  return policy.mode === 'allowlist'
    ? policy.system.includes(namespace)
    : !policy.system.includes(namespace)
}

function requiresWorkspace(
  binding: AuthenticatedRuntimeBinding | null
): binding is AuthenticatedRuntimeBinding {
  return binding !== null && typeof binding.workspaceId === 'string' && binding.workspaceId.length > 0
}

function requiresAiCliBinding(
  binding: AuthenticatedRuntimeBinding | null
): binding is AuthenticatedRuntimeBinding {
  return (
    requiresWorkspace(binding) &&
    typeof binding.instanceId === 'string' &&
    binding.instanceId.length > 0 &&
    typeof binding.audience === 'string' &&
    binding.audience.length > 0
  )
}

/** Pure Issue 03 authorization seam. It returns a plan only; process, PTY,
 * backend, and Electron side effects belong to later Host adapters. */
export function planPublicCapabilityCall(
  call: CapabilityCall,
  policy: Extract<PluginCapabilityPolicy, { kind: 'manifest-v2' }>,
  context: HostCapabilityContext
): PublicCapabilityDecision {
  const address = `${call.ns}.${call.method}`
  const entry = publicCapabilityEntry(address)
  if (!entry || entry.kind !== 'method') {
    return publicDenied(call.reqId, 'METHOD_NOT_FOUND', `unknown public capability '${address}'`)
  }

  if (entry.storage === true) {
    // Storage is Host-granted and deliberately absent from Manifest v2's
    // `permissions.system` namespace array.
  } else if (entry.namespace === 'shell') {
    if (!policy.shell) return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'shell access is not declared')
  } else if (!policy.system.includes(entry.namespace)) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', `system namespace '${entry.namespace}' is not declared`)
  }

  if (entry.eligibility === 'firstParty' && !context.publisherEligible) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'publisher is not eligible for this capability')
  }

  if (entry.storage === true) {
    return planStoragePartition(call, context)
  }

  const binding = context.runtimeBinding
  if (!binding || binding.pluginId !== call.pluginId) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'authenticated runtime binding is missing')
  }
  if (entry.scope === 'workspace' && !requiresWorkspace(binding)) {
    return publicDenied(call.reqId, 'WORKSPACE_SCOPE_VIOLATION', 'workspace binding is required')
  }
  if (entry.namespace === 'aiCli' && !requiresAiCliBinding(binding)) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'AI CLI view binding is required')
  }

  const grant = context.userGrant
  if (!grant || grant.packageVersion !== binding.packageVersion) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'package-version grant is missing')
  }
  if (entry.namespace === 'shell') {
    if (grant.shell !== policy.shell) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'shell mode is not user-approved')
    }
    if (policy.shell === 'full' && grant.highRiskShellConfirmed !== true) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'full shell requires high-risk confirmation')
    }
  } else if (!grant.system.includes(entry.namespace)) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', `system namespace '${entry.namespace}' is not user-approved`)
  }

  const args = publicRequestArgs(call)
  if (!args || !entry.validateRequest?.(args)) {
    return publicDenied(call.reqId, 'INVALID_ARGUMENT', `invalid request for '${address}'`)
  }
  if (
    entry.address === 'aiCli.startSession' &&
    (!context.aiCliProfiles || !context.aiCliProfiles.includes(String(args.profileId)))
  ) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'AI CLI profile is not Host-allowlisted')
  }

  const initiator = context.initiator
  if (initiator !== undefined && !isAuthenticatedInitiator(initiator)) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'authenticated initiator is invalid')
  }
  if (
    !executionPolicyAllows(
      initiator,
      context.executionPolicy,
      entry.namespace,
      entry.namespace === 'shell' ? String(args.command) : undefined,
    )
  ) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'agent execution policy denied the operation')
  }

  let session: AuthenticatedRuntimeBinding | undefined
  if (entry.address === 'aiCli.cancelStart') {
    const requestId = args.requestId
    const pending =
      typeof requestId === 'string' && context.pendingStartBindings
        ? context.pendingStartBindings.get(requestId)
        : undefined
    if (!pending || !sameBinding(pending, binding)) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'AI CLI start request ownership mismatch')
    }
  }
  if (entry.namespace === 'aiCli' && 'sessionId' in args) {
    const sessionId = args.sessionId
    if (typeof sessionId !== 'string' || !context.sessionBindings) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'AI CLI session is not Host-bound')
    }
    session = context.sessionBindings.get(sessionId)
    if (!session || !sameBinding(session, binding)) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'AI CLI session ownership mismatch')
    }
  }

  if (entry.namespace === 'shell' && policy.shell === 'allowlist') {
    if (!shellCommandAllowed(String(args.command), HOST_SHELL_EXECUTABLE_ALLOWLIST)) {
      return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'shell executable is not Host-allowlisted')
    }
  }

  return {
    kind: 'allow',
    plan: {
      kind: 'public',
      address,
      scope: entry.scope,
      args,
      runtime: binding,
      ...(initiator ? { initiator } : {}),
      ...(initiator && context.executionPolicy
        ? { policyRevision: context.executionPolicy.revision }
        : {}),
      ...(policy.shell && entry.namespace === 'shell' ? { shellMode: policy.shell } : {}),
      ...(session ? { session } : {}),
    },
  }
}

/** Select the versioned storage snapshot whose package version matches the
 *  binding's. Only a snapshot bound to `packageVersion` may be selected; a
 *  binding whose package version matches no stored snapshot fails closed. */
function selectStorageSnapshot(
  pluginId: string,
  packageVersion: string,
  tier: StorageSnapshotTier | undefined,
  storageSnapshots: ReadonlyMap<StorageSnapshotTier, string> | undefined
): StorageSnapshotRef | null {
  if (!storageSnapshots || !tier) return null
  if (!['candidate', 'active', 'previous'].includes(tier)) return null
  for (const [candidateTier, version] of storageSnapshots) {
    if (
      !['candidate', 'active', 'previous'].includes(candidateTier) ||
      typeof version !== 'string' ||
      version.length === 0
    ) {
      return null
    }
  }
  if (storageSnapshots.get(tier) !== packageVersion) return null
  return { pluginId, tier, packageVersion }
}

/** Host-managed storage planning. A storage call selects only a partition
 *  class (plugin|workspace) and a key; the Host derives the partition identity
 *  from the authenticated runtime binding and selects the versioned snapshot
 *  whose package version matches the binding. The Plugin never supplies, and
 *  can never override, any partition identity. */
function planStoragePartition(
  call: CapabilityCall,
  context: HostCapabilityContext
): PublicCapabilityDecision {
  const address = `${call.ns}.${call.method}`
  const initiator = context.initiator
  if (initiator !== undefined && !isAuthenticatedInitiator(initiator)) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'authenticated initiator is invalid')
  }
  const grant = context.userGrant
  const binding = context.runtimeBinding

  if (!binding || binding.pluginId !== call.pluginId) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'authenticated runtime binding is missing')
  }

  if (
    !grant ||
    grant.packageVersion !== binding.packageVersion ||
    grant.storage !== true
  ) {
    return publicDenied(call.reqId, 'CAPABILITY_DENIED', 'storage grant is not user-approved')
  }

  const args = publicRequestArgs(call)
  // Storage accepts only { scope, key }. Any partition identity the Plugin
  // might try to supply (pluginId, workspaceId, packageVersion, path) is
  // rejected because storageRequestValidationError allows only those keys.
  if (!args) {
    return publicDenied(call.reqId, 'INVALID_ARGUMENT', `invalid request for '${address}'`)
  }
  const requestError = storageRequestValidationError(
    args,
    address as 'storage.get' | 'storage.set' | 'storage.delete'
  )
  if (requestError) {
    return publicDenied(call.reqId, requestError, `invalid request for '${address}'`)
  }

  const partitionClass = args.scope as StoragePartitionClass
  const key = args.key as string

  if (partitionClass !== 'plugin' && !requiresWorkspace(binding)) {
    return publicDenied(call.reqId, 'WORKSPACE_SCOPE_VIOLATION', 'workspace binding is required')
  }

  const partition: StoragePartition =
    partitionClass === 'plugin'
      ? { pluginId: binding.pluginId, workspaceId: null, key }
      : { pluginId: binding.pluginId, workspaceId: binding.workspaceId ?? null, key }

  const snapshot = selectStorageSnapshot(
    binding.pluginId,
    binding.packageVersion,
    context.storageSnapshotTier,
    context.storageSnapshots
  )
  if (!snapshot) {
    return publicDenied(
      call.reqId,
      'CAPABILITY_DENIED',
      'no storage snapshot matches this package version'
    )
  }

  return {
    kind: 'allow',
    plan: {
      kind: 'public',
      address,
      scope: partitionClass,
      args,
      runtime: binding,
      storage: { partition, snapshot },
      ...(initiator ? { initiator } : {}),
    },
  }
}

/** Route a cataloged event only to the Host-authenticated package audience. */
export function isPublicCapabilityEventAllowed(
  policy: Extract<PluginCapabilityPolicy, { kind: 'manifest-v2' }>,
  event: string,
  payload: unknown,
  context: HostCapabilityContext,
  targetPluginId: string,
  sourceBinding?: AuthenticatedRuntimeBinding
): boolean {
  const entry = publicCapabilityEntry(event)
  if (!entry || entry.kind !== 'event') return false
  if (!policy.system.includes(entry.namespace as PluginSystemNamespace)) return false
  if (entry.eligibility === 'firstParty' && !context.publisherEligible) return false
  const binding = context.runtimeBinding
  if (!binding || !requiresWorkspace(binding)) return false
  const grant = context.userGrant
  if (
    !grant ||
    grant.packageVersion !== binding.packageVersion ||
    !grant.system.includes(entry.namespace as PluginSystemNamespace)
  ) {
    return false
  }
  if (typeof targetPluginId !== 'string' || targetPluginId.length === 0) return false
  if (targetPluginId !== binding.pluginId) return false
  if (event === 'workspace.filesChanged') {
    if (
      !sourceBinding ||
      sourceBinding.pluginId !== HOST_EVENT_SOURCE_PLUGIN_ID ||
      !requiresWorkspace(sourceBinding) ||
      sourceBinding.packageVersion.length === 0 ||
      sourceBinding.instanceId !== null ||
      sourceBinding.audience !== null ||
      sourceBinding.workspaceId !== binding.workspaceId ||
      sourceBinding.packageVersion !== binding.packageVersion
    ) {
      return false
    }
    return (
      isRecord(payload) &&
      Object.keys(payload).every((key) => key === 'changes') &&
      Array.isArray(payload.changes) &&
      payload.changes.every(
        (change) =>
          isRecord(change) &&
          Object.keys(change).every((key) => key === 'path' || key === 'kind') &&
          typeof change.path === 'string' &&
          ['created', 'changed', 'deleted'].includes(String(change.kind))
      )
    )
  }
  if (event !== 'aiCli.output' && event !== 'aiCli.exited') return false
  if (!sourceBinding || !sameBinding(sourceBinding, binding)) return false
  if (!requiresAiCliBinding(binding) || !isRecord(payload)) return false
  if (!context.sessionBindings) return false
  if (event === 'aiCli.output') {
    return (
      Object.keys(payload).every((key) => key === 'sessionId' || key === 'data') &&
      typeof payload.data === 'string' &&
      typeof payload.sessionId === 'string' &&
      context.sessionBindings.get(payload.sessionId) !== undefined &&
      sameBinding(context.sessionBindings.get(payload.sessionId)!, binding)
    )
  }
  if (
    Object.keys(payload).some((key) => key !== 'sessionId' && key !== 'exitCode') ||
    typeof payload.sessionId !== 'string' ||
    !Object.prototype.hasOwnProperty.call(payload, 'exitCode') ||
    (payload.exitCode !== null &&
      !(typeof payload.exitCode === 'number' && Number.isInteger(payload.exitCode)))
  ) {
    return false
  }
  const sessionId = payload.sessionId
  if (typeof sessionId !== 'string' || !context.sessionBindings) return false
  const session = context.sessionBindings.get(sessionId)
  return session !== undefined && sameBinding(session, binding)
}

/**
 * A decision about how to service a capability call. `respond` carries a
 * ready-made envelope (deny / built-in ping / unknown); `backend` names the
 * backend WS message type the manager should dispatch and await; `host` names
 * a main-process action from {@link HOST_CAPABILITIES}.
 */
export type CapabilityPlan =
  | { kind: 'respond'; response: CapabilityResponse }
  | { kind: 'backend'; wsType: string }
  | { kind: 'host'; action: string }
  | PublicCapabilityExecutionPlan

/**
 * M2 dispatch planner. Enforces scoping first (an un-granted namespace is
 * denied here and never reaches the backend), then routes:
 *   - `ping`            → in-process success (M1 built-in)
 *   - mapped `(ns,m)`   → `backend` with the WS type from {@link resolveWsType}
 *   - anything else     → `UNKNOWN`
 */
export function planCapabilityCall(
  call: CapabilityCall,
  policy: CapabilityPolicyInput,
  authorization?: HostCapabilityContext
): CapabilityPlan {
  if (isManifestV2Policy(policy)) {
    if (!authorization) {
      return {
        kind: 'respond',
        response: buildError(call.reqId, 'CAPABILITY_DENIED', 'Host authorization context is missing'),
      }
    }
    const decision = planPublicCapabilityCall(call, policy, authorization)
    return decision.kind === 'allow'
      ? decision.plan
      : { kind: 'respond', response: decision.response }
  }
  if (!isCallAllowed(policy, call.ns, call.method)) {
    const label =
      isRequirementsArray(policy) || isLegacyPolicy(policy)
        ? call.ns
        : `${call.ns}.${call.method}`
    return {
      kind: 'respond',
      response: buildError(
        call.reqId,
        'CAP_DENIED',
        `capability '${label}' not granted`
      ),
    }
  }
  if (call.ns === 'ping') {
    return { kind: 'respond', response: buildSuccess(call.reqId, { pong: true, echo: call.args }) }
  }
  const hostAction = HOST_CAPABILITIES[`${call.ns}.${call.method}`]
  if (hostAction) {
    return { kind: 'host', action: hostAction }
  }
  const wsType = resolveWsType(call.ns, call.method)
  if (!wsType) {
    return {
      kind: 'respond',
      response: buildError(call.reqId, 'UNKNOWN', `no handler for '${call.ns}.${call.method}'`),
    }
  }
  return { kind: 'backend', wsType }
}

/** Map a backend WS response envelope into the plugin-facing capability
 *  envelope, preserving the correlation id the plugin is awaiting. */
export function backendResponseToCapability(
  reqId: string,
  resp: WsResponse
): CapabilityResponse {
  if (resp.ok) return buildSuccess(reqId, resp.payload)
  const code = resp.error?.code === 'RESOURCE_LIMIT' ? 'RESOURCE_LIMIT' : 'BACKEND_ERROR'
  return buildError(reqId, code, resp.error?.message ?? 'backend request failed')
}

// ── Terminal PTY routing + output micro-batching ─────────────────────────────

/** WS request types whose successful responses bind PTY sessions to the calling
 *  plugin (see {@link terminalSessionsFromResponse}). */
export const TERMINAL_ROUTE_WS_TYPES: readonly string[] = ['terminal.create', 'terminal.reattach']

/** The ONLY WS types the fire-and-forget cast channel may dispatch — the
 *  per-keystroke input path and its log marker. Main-side enforcement mirroring
 *  the shims' CAST_TYPES: everything else must go through the request/response
 *  channel so errors surface, and a compromised view cannot spray arbitrary
 *  unacknowledged backend traffic. */
export const CASTABLE_WS_TYPES: ReadonlySet<string> = new Set([
  'terminal.input',
  'terminal.log_sent',
])

/**
 * PTY session ids a successful backend response binds to the calling plugin:
 * `terminal.create` yields its new `terminal_session_id`, `terminal.reattach`
 * yields every id in `alive[]` (the reattach re-claims those PTYs' output for
 * the broker transport, on behalf of the plugin that asked). Anything else —
 * other WS types, malformed payloads — yields nothing.
 */
export function terminalSessionsFromResponse(wsType: string, result: unknown): string[] {
  if (typeof result !== 'object' || result === null) return []
  const r = result as Record<string, unknown>
  if (wsType === 'terminal.create') {
    return typeof r.terminal_session_id === 'string' && r.terminal_session_id
      ? [r.terminal_session_id]
      : []
  }
  if (wsType === 'terminal.reattach') {
    return Array.isArray(r.alive)
      ? r.alive.filter((id): id is string => typeof id === 'string' && id.length > 0)
      : []
  }
  return []
}

/** The `terminal_session_id` of a terminal.* event payload, or '' when absent. */
export function terminalSessionIdOf(payload: unknown): string {
  if (typeof payload !== 'object' || payload === null) return ''
  const id = (payload as Record<string, unknown>).terminal_session_id
  return typeof id === 'string' ? id : ''
}

export interface TerminalOutputBatcher {
  /** Queue one terminal.output payload; delivery happens at the next flush. */
  push(sessionId: string, payload: Record<string, unknown>): void
  /** Deliver the session's pending batch now (ordering barrier before exit). */
  flushSession(sessionId: string): void
  /** Discard a session's pending batch without delivering (owner torn down). */
  dropSession(sessionId: string): void
  /** Deliver every pending batch now. */
  flushAll(): void
}

/**
 * Per-session micro-batcher for `terminal.output` events crossing the broker.
 * PTY output arrives as a dense stream of small events; forwarding each one
 * through a separate `webContents.send` floods the plugin view's IPC channel.
 * Batching per `terminal_session_id` over a short window (default 12 ms)
 * concatenates the `data` chunks — Uint8Array raw PTY bytes on the binary
 * frame path (any byte boundary is safe: the consumer's xterm runs a
 * streaming UTF-8 decoder), or legacy complete JS strings — and keeps every
 * other field (including `sequence`) from the LAST queued payload: the
 * batch's data covers exactly the events up to that sequence, and the frontend
 * consumer (useTerminal) reads only `terminal_session_id` + `data`.
 *
 * Ordering: one entry per session means intra-session order is preserved;
 * callers must `flushSession` before delivering a `terminal.exit` so batched
 * output never lands after the exit notice.
 */
export function createTerminalOutputBatcher(
  deliver: (sessionId: string, payload: Record<string, unknown>) => void,
  flushMs = 12
): TerminalOutputBatcher {
  interface Entry {
    chunks: (string | Uint8Array)[]
    last: Record<string, unknown>
    timer: ReturnType<typeof setTimeout>
  }
  const pending = new Map<string, Entry>()

  function combine(chunks: (string | Uint8Array)[]): string | Uint8Array {
    if (chunks.every((c): c is string => typeof c === 'string')) return chunks.join('')
    // Mixed or binary batch: normalize to one Uint8Array.
    const enc = new TextEncoder()
    const parts = chunks.map((c) => (typeof c === 'string' ? enc.encode(c) : c))
    const total = parts.reduce((n, p) => n + p.length, 0)
    const out = new Uint8Array(total)
    let off = 0
    for (const p of parts) {
      out.set(p, off)
      off += p.length
    }
    return out
  }

  function flushSession(sessionId: string): void {
    const entry = pending.get(sessionId)
    if (!entry) return
    clearTimeout(entry.timer)
    pending.delete(sessionId)
    deliver(sessionId, { ...entry.last, data: combine(entry.chunks) })
  }

  function push(sessionId: string, payload: Record<string, unknown>): void {
    const data =
      typeof payload.data === 'string' || payload.data instanceof Uint8Array
        ? payload.data
        : ''
    const entry = pending.get(sessionId)
    if (entry) {
      entry.chunks.push(data)
      entry.last = payload
      return
    }
    pending.set(sessionId, {
      chunks: [data],
      last: payload,
      timer: setTimeout(() => flushSession(sessionId), flushMs),
    })
  }

  function dropSession(sessionId: string): void {
    const entry = pending.get(sessionId)
    if (!entry) return
    clearTimeout(entry.timer)
    pending.delete(sessionId)
  }

  function flushAll(): void {
    for (const sessionId of [...pending.keys()]) flushSession(sessionId)
  }

  return { push, flushSession, dropSession, flushAll }
}
