// Dedicated preload for plugin `WebContentsView`s.
//
// Deliberately minimal: it exposes ONLY `window.nav` (brokered capability and
// package-local backend calls, events, and lifecycle helpers). It must NOT
// expose `window.agentTeam` or any of the host's privileged surface — a plugin
// reaches the host solely through brokered calls.
// Node-free by design (request ids come from webcrypto) so it runs under
// `sandbox: true`.

import { contextBridge, ipcRenderer } from 'electron'

// The manager injects `--plugin-id=<id>` via webPreferences.additionalArguments,
// so the id is authoritative (main also verifies by sender) and not spoofable
// from page content.
const PLUGIN_ID_PREFIX = '--plugin-id='
const PACKAGE_BACKEND_PREFIX = '--plugin-backend='
const pluginId =
  process.argv.find((a) => a.startsWith(PLUGIN_ID_PREFIX))?.slice(PLUGIN_ID_PREFIX.length) ?? ''
const packageBackendEnabled = process.argv.includes(`${PACKAGE_BACKEND_PREFIX}1`)

interface CapabilityResponse {
  reqId: string
  ok: boolean
  result?: unknown
  error?: { code: string; message?: string }
}

interface BackendSubscriptionRegistration {
  readonly ready: Promise<void>
  readonly settled: Promise<void>
  dispose(): void
}

type EventListener = (data: unknown) => void
const listeners = new Map<string, Set<EventListener>>()
type BackendEventListener = (data: unknown) => void
const backendSubscriptions = new Map<string, {
  event: string
  listener: BackendEventListener
  settle(error?: Error): void
}>()

ipcRenderer.on('plugin:cap:event', (_event, payload: { type: string; data: unknown }) => {
  listeners.get(payload.type)?.forEach((cb) => cb(payload.data))
})

ipcRenderer.on(
  'plugin:backend:event',
  (_event, payload: { subscriptionId: string; event: string; payload: unknown }) => {
    const subscription = backendSubscriptions.get(payload.subscriptionId)
    if (!subscription || subscription.event !== payload.event) return
    subscription.listener(payload.payload)
  },
)

ipcRenderer.on(
  'plugin:backend:status',
  (_event, payload: { subscriptionId: string; ok: boolean; error?: { code: string; message?: string } }) => {
    if (!payload || typeof payload.subscriptionId !== 'string' || payload.ok !== false) return
    const subscription = backendSubscriptions.get(payload.subscriptionId)
    if (!subscription) return
    const error = new Error(
      payload.error?.message ?? 'Plugin backend subscription ended.',
    ) as Error & { code?: string }
    error.code = payload.error?.code ?? 'BACKEND_UNAVAILABLE'
    subscription.settle(error)
  },
)

const nav = {
  /** Call a host capability. Resolves with the response envelope. */
  callCapability(ns: string, method: string, args?: unknown): Promise<CapabilityResponse> {
    return ipcRenderer.invoke('plugin:cap:call', {
      pluginId,
      ns,
      method,
      args,
      reqId: globalThis.crypto.randomUUID(),
    })
  },
  /** Fixed Host-owned first-party action bridge used by the bundled Git
   *  package for its existing Git/Issues adapters. The main process validates
   *  the sender, action, method, and workspace before dispatch. */
  callHostAction(action: string, args?: unknown): Promise<CapabilityResponse> {
    return ipcRenderer.invoke('plugin:host:call', {
      action,
      args,
      reqId: globalThis.crypto.randomUUID(),
    })
  },
  /** Fire-and-forget capability call: no response envelope ever comes back.
   *  Used for the per-keystroke terminal.input path, where a request/response
   *  round-trip per key would eat the typing-latency budget. Scoping is still
   *  enforced by the broker (a denied/unmapped cast is silently dropped). */
  castCapability(ns: string, method: string, args?: unknown): void {
    ipcRenderer.send('plugin:cap:cast', {
      pluginId,
      ns,
      method,
      args,
      reqId: globalThis.crypto.randomUUID(),
    })
  },
  /** Call the authenticated package-local Backend Wire child. Identity is
   *  resolved from the sender-bound view in Electron main; this bridge accepts
   * only the opaque request id generated by the SDK. */
  callBackend(
    reqId: string,
    name: string,
    args: unknown,
    timeoutMs?: number,
  ): Promise<CapabilityResponse> {
    return ipcRenderer.invoke('plugin:backend:call', { reqId, name, args, timeoutMs })
  },
  /** Cancel one exact package-local backend request. */
  cancelBackend(reqId: string): void {
    ipcRenderer.send('plugin:backend:cancel', { reqId })
  },
  /** Subscribe to one package-local backend event. The SDK owns the public
   *  Disposable; preload keeps the subscription id private to this sender and
   *  exposes Host acceptance so callers can retain a fallback until ready. */
  subscribeBackend(
    event: string,
    listener: BackendEventListener,
  ): BackendSubscriptionRegistration {
    const subscriptionId = globalThis.crypto.randomUUID()
    let active = true
    let resolveSettled!: () => void
    let rejectSettled!: (error: unknown) => void
    const settled = new Promise<void>((resolve, reject) => {
      resolveSettled = resolve
      rejectSettled = reject
    })
    const settle = (error?: Error): void => {
      if (!active) return
      active = false
      backendSubscriptions.delete(subscriptionId)
      if (error) rejectSettled(error)
      else resolveSettled()
    }
    const dispose = (): void => {
      if (!active) return
      settle()
      ipcRenderer.send('plugin:backend:cancel', { subscriptionId })
    }
    backendSubscriptions.set(subscriptionId, { event, listener, settle })
    const ready = ipcRenderer.invoke('plugin:backend:subscribe', { subscriptionId, event })
      .then((response: CapabilityResponse) => {
        if (!response || response.reqId !== subscriptionId || typeof response.ok !== 'boolean') {
          const error = new Error(
            'Plugin backend returned an invalid subscription response.',
          ) as Error & { code?: string }
          error.code = 'PROTOCOL_ERROR'
          throw error
        }
        if (!response.ok) {
          const error = new Error(
            response.error?.message ?? 'Plugin backend subscription failed.',
          ) as Error & { code?: string }
          error.code = response.error?.code ?? 'BACKEND_UNAVAILABLE'
          throw error
        }
      })
      .catch((error: unknown) => {
        dispose()
        throw error
      })
    return { ready, settled, dispose }
  },
  /** Subscribe to host-pushed events of a given type. Returns a disposer. */
  on(type: string, cb: EventListener): () => void {
    let set = listeners.get(type)
    if (!set) {
      set = new Set()
      listeners.set(type, set)
    }
    set.add(cb)
    return () => set!.delete(cb)
  },
  /** Announce the plugin has mounted. */
  ready(): void {
    ipcRenderer.send('plugin:ready')
  },
  /** Ask the host to dismiss (hide) this plugin's own view. Sender-scoped in
   *  main: a view can only ever hide itself. */
  hideSelf(): void {
    ipcRenderer.send('plugin:hideSelf')
  },
  /** Subscribe to host-pushed open targets — entry-query-shaped params
   *  delivered to an already-running view instead of a reload (so in-page
   *  state such as open tabs survives). Returns a disposer. */
  onOpenTarget(cb: (params: Record<string, string>) => void): () => void {
    const listener = (_event: unknown, params: Record<string, string>): void => cb(params)
    ipcRenderer.on('plugin:openTarget', listener)
    return () => {
      ipcRenderer.removeListener('plugin:openTarget', listener)
    }
  },
}

if (!packageBackendEnabled) {
  const privateSurface = nav as Omit<
    typeof nav,
    'callBackend' | 'cancelBackend' | 'subscribeBackend'
  > & Partial<Pick<typeof nav, 'callBackend' | 'cancelBackend' | 'subscribeBackend'>>
  delete privateSurface.callBackend
  delete privateSurface.cancelBackend
  delete privateSurface.subscribeBackend
}

contextBridge.exposeInMainWorld('nav', nav)
