"""Characterization: the wizard's agent-CLI install entries survive the
one-file-per-vendor move byte-for-byte.

The snapshot below was generated from the pre-move DEPS table. It pins ids,
ORDER, and every field of every agent_cli entry, so the per-vendor relocation
(spec.install_dep) is provably a pure move. Update it only when an entry is
deliberately changed.

`platforms` and `install_cmds` were added to `Dep` for the Linux port and are
empty for every agent CLI — their install commands (npm, curl) are the same
everywhere. A vendor that quietly became platform-specific would change one
of these two, which is exactly what this snapshot is here to catch."""

import dataclasses

from agent_team_backend.onboarding_deps import DEPS

SNAPSHOT = [{'id': 'claude',
  'label': 'Claude Code',
  'description': 'Anthropic Claude CLI',
  'group': 'agent_cli',
  'check_cmd': ['claude', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'npm install -g @anthropic-ai/claude-code',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://platform.claude.com/docs/claude-code',
  'requires_binaries': ['npm'],
  'update_cmd': 'claude update',
  'doctor_cmd': 'claude doctor',
  'npm_package': '@anthropic-ai/claude-code',
  'update_state_file': '.last-update-result.json',
  'config_home_env': 'CLAUDE_CONFIG_DIR',
  'config_home_default': '.claude',
  'autoupdate_env': 'DISABLE_AUTOUPDATER',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'codex',
  'label': 'Codex',
  'description': 'OpenAI Codex CLI',
  'group': 'agent_cli',
  'check_cmd': ['codex', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'npm install -g @openai/codex',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://learn.chatgpt.com/docs/codex/cli',
  'requires_binaries': ['npm'],
  'update_cmd': 'codex update',
  'doctor_cmd': 'codex doctor',
  'npm_package': '@openai/codex',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'antigravity',
  'label': 'Antigravity',
  'description': 'Google Antigravity CLI',
  'group': 'agent_cli',
  'check_cmd': ['agy', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -fsSL https://antigravity.google/cli/install.sh | bash',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://antigravity.google/docs/cli-getting-started',
  'requires_binaries': ['curl'],
  'update_cmd': 'agy update',
  'doctor_cmd': '',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'grok',
  'label': 'Grok CLI',
  'description': 'superagent-ai Grok coding agent',
  'group': 'agent_cli',
  'check_cmd': ['grok', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -fsSL '
                 'https://raw.githubusercontent.com/superagent-ai/grok-cli/main/install.sh '
                 '| bash',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://github.com/superagent-ai/grok-cli',
  'requires_binaries': ['curl'],
  'update_cmd': 'grok update',
  'doctor_cmd': '',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'kimi',
  'label': 'Kimi Code',
  'description': 'Moonshot AI Kimi Code CLI',
  'group': 'agent_cli',
  'check_cmd': ['kimi', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -fsSL https://code.kimi.com/kimi-code/install.sh | bash',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://moonshotai.github.io/kimi-code/',
  'requires_binaries': ['curl'],
  'update_cmd': 'kimi upgrade',
  'doctor_cmd': 'kimi doctor',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'opencode',
  'label': 'OpenCode',
  'description': 'OpenCode terminal coding agent',
  'group': 'agent_cli',
  'check_cmd': ['opencode', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -fsSL https://opencode.ai/install | bash',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://opencode.ai/docs',
  'requires_binaries': ['curl'],
  'update_cmd': 'opencode upgrade',
  'doctor_cmd': '',
  'npm_package': 'opencode-ai',
  'update_state_file': '',
  'config_home_env': 'OPENCODE_CONFIG_DIR',
  'config_home_default': '',
  'autoupdate_env': 'OPENCODE_DISABLE_AUTOUPDATE',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'kilo',
  'label': 'Kilo Code',
  'description': 'Kilo Code terminal coding agent (OpenCode fork)',
  'group': 'agent_cli',
  'check_cmd': ['kilo', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'npm install -g @kilocode/cli',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://kilo.ai/docs/code-with-ai/platforms/cli',
  'requires_binaries': ['npm'],
  'update_cmd': 'kilo upgrade',
  'doctor_cmd': '',
  'npm_package': '@kilocode/cli',
  'update_state_file': '',
  'config_home_env': 'KILO_CONFIG_DIR',
  'config_home_default': '',
  'autoupdate_env': 'KILO_DISABLE_AUTOUPDATE',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'qwen',
  'label': 'Qwen Code',
  'description': 'Alibaba Qwen Code coding agent CLI',
  'group': 'agent_cli',
  'check_cmd': ['qwen', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'npm install -g @qwen-code/qwen-code',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://qwenlm.github.io/qwen-code-docs/',
  'requires_binaries': ['npm'],
  'update_cmd': 'qwen update',
  'doctor_cmd': '',
  'npm_package': '@qwen-code/qwen-code',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'pi',
  'label': 'Pi',
  'description': 'Pi coding agent CLI',
  'group': 'agent_cli',
  'check_cmd': ['pi', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'npm install -g --ignore-scripts @earendil-works/pi-coding-agent',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://pi.dev/docs',
  'requires_binaries': ['npm'],
  'update_cmd': 'pi update',
  'doctor_cmd': '',
  'npm_package': '@earendil-works/pi-coding-agent',
  'update_state_file': '',
  'config_home_env': 'PI_CODING_AGENT_DIR',
  'config_home_default': '',
  'autoupdate_env': 'PI_SKIP_VERSION_CHECK',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'copilot',
  'label': 'Copilot CLI',
  'description': 'GitHub Copilot coding agent CLI',
  'group': 'agent_cli',
  'check_cmd': ['copilot', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'brew install --cask copilot-cli',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://docs.github.com/en/copilot/how-tos/use-copilot-agents/use-copilot-cli',
  'requires_binaries': ['brew'],
  'update_cmd': 'copilot update',
  'doctor_cmd': '',
  'npm_package': '@github/copilot',
  'update_state_file': '',
  'config_home_env': 'COPILOT_HOME',
  'config_home_default': '',
  'autoupdate_env': 'COPILOT_AUTO_UPDATE',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'cursor',
  'label': 'Cursor CLI',
  'description': 'Cursor terminal coding agent CLI',
  'group': 'agent_cli',
  'check_cmd': ['agent', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': ['cursor-agent'],
  'min_version': '',
  'install_cmd': 'curl https://cursor.com/install -fsS | bash',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://cursor.com/docs/cli',
  'requires_binaries': ['curl'],
  'update_cmd': 'agent update',
  'doctor_cmd': '',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'aider',
  'label': 'Aider',
  'description': 'Aider AI pair-programming CLI',
  'group': 'agent_cli',
  'check_cmd': ['aider', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -LsSf https://aider.chat/install.sh | sh',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://aider.chat',
  'requires_binaries': ['curl'],
  'update_cmd': 'aider --upgrade',
  'doctor_cmd': '',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': 'AIDER_CHECK_UPDATE',
  'platforms': [],
  'install_cmds': {}},
 # Appended after the snapshot was taken: muse is absent from
 # _AGENT_CLI_ORDER, so it sorts last in registry order.
 {'id': 'droid',
  'label': 'Droid',
  'description': 'Factory AI coding agent',
  'group': 'agent_cli',
  'check_cmd': ['droid', '--version'],
  'version_regex': '(\\d+\\.\\d+\\.\\d+)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'brew install --cask droid',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://docs.factory.ai/cli/getting-started/overview',
  'requires_binaries': ['brew'],
  'update_cmd': 'droid update',
  'doctor_cmd': 'droid doctor',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '.factory',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}},
 {'id': 'muse',
  'label': 'Muse Code',
  'description': 'Meta Muse Code CLI',
  'group': 'agent_cli',
  'check_cmd': ['muse', '--version'],
  'version_regex': '(\\d+\\.\\d+(?:\\.\\d+)?)',
  'alt_commands': [],
  'min_version': '',
  'install_cmd': 'curl -fsSL https://dev.meta.ai/install.sh | sh',
  'needs_terminal': True,
  'optional': True,
  'docs_url': 'https://developer.meta.com/ai/products/muse-code/',
  'requires_binaries': ['curl'],
  'update_cmd': '',
  'doctor_cmd': '',
  'npm_package': '',
  'update_state_file': '',
  'config_home_env': '',
  'config_home_default': '',
  'autoupdate_env': '',
  'platforms': [],
  'install_cmds': {}}]


def test_agent_cli_install_entries_unchanged():
    actual = [dataclasses.asdict(d) for d in DEPS if d.group == "agent_cli"]
    # asdict keeps tuples; the snapshot stores lists — normalize before comparing.
    actual = [
        {k: list(v) if isinstance(v, tuple) else v for k, v in entry.items()}
        for entry in actual
    ]
    assert actual == SNAPSHOT
