"""Per-workspace project metadata + per-run pipeline event logs.

Each workspace gets a `.agent-team/` directory containing:
  - project.json                                 current pipeline state, atomic-write
  - pipeline-YYYYMMDD-HHMMSS-<task-slug>.log    one log file per pipeline run
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

log = logging.getLogger("agent_team_backend.projects")

PROJECT_DIR_NAME = ".agent-team"
PROJECT_FILE = "project.json"
RUNS_SUBDIR = "runs"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _make_run_name(task_description: str) -> str:
    """Generate YYYYMMDD-HHMMSS-<slug> — used as the run sub-folder name."""
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    # Keep only CJK / alphanumeric chars, replace the rest with hyphens, max 30 chars
    slug = re.sub(r"[^\w一-鿿぀-ヿ]", "-", task_description.strip())
    slug = re.sub(r"-+", "-", slug).strip("-")[:30]
    return f"{ts}-{slug}" if slug else ts


def _make_log_filename(task_description: str) -> str:
    """Return relative path 'runs/{run_name}/pipeline.log' for a new pipeline run."""
    run_name = _make_run_name(task_description)
    return f"{RUNS_SUBDIR}/{run_name}/pipeline.log"


def _project_id_for(workspace_path: str) -> str:
    h = hashlib.sha1(workspace_path.encode("utf-8")).hexdigest()[:10]
    return f"proj_{h}"


# tmux session names generated by terminals.py follow this format.
# Validated before persistence to guard against project.json tampering.
_TMUX_NAME_RE = re.compile(r"^at-[A-Za-z0-9]{1,32}$")


@dataclass
class SlotRecord:
    label: str
    agent: str = ""
    role: str = ""
    pane_id: str | None = None
    spawn_status: str = "pending"   # pending / spawned / removed
    kickoff_status: str = "none"    # none / sent / failed
    # CLI session id used to resume this slot's conversation on App restart.
    # Claude: the --session-id we pinned at spawn (known immediately).
    # Codex/Gemini: the CLI-generated id, detected after spawn. "" = no resume.
    session_id: str = ""
    # tmux session name when spawned via tmux; "" = plain PTY (no tmux).
    tmux_name: str = ""


@dataclass
class ManualPaneRecord:
    pane_id: str
    agent: str = ""
    role: str = ""
    command: str = ""
    spawn_status: str = "spawned"  # spawned / removed
    session_id: str = ""
    # tmux session name when spawned via tmux; "" = plain PTY (no tmux).
    tmux_name: str = ""


@dataclass
class StageRecord:
    stage_id: str
    title: str = ""
    agent: str = ""
    role: str = ""
    pane_id: str | None = None
    status: str = "pending"  # pending / running / completed / aborted
    started_at: str | None = None
    ended_at: str | None = None
    slots: list[SlotRecord] = field(default_factory=list)


@dataclass
class Project:
    id: str
    name: str
    workspace_path: str
    created_at: str
    updated_at: str
    task_description: str = ""
    state: str = "idle"  # idle / running / completed / aborted
    current_stage_index: int = -1
    total_stages: int = 5
    stages: list[StageRecord] = field(default_factory=list)
    manual_panes: list[ManualPaneRecord] = field(default_factory=list)
    agents_spawned: int = 0
    backend_version: str = ""
    log_file_name: str = ""  # set by start_pipeline(); e.g. "pipeline-20260527-183000-建立登入頁面.log"
    layout_mode: str = "grid"
    pipeline_id: str = ""  # which pipeline template was used for this run
    run_count: int = 0     # incremented on each successful pipeline completion
    theme: str = "dark-github"  # backup of the user-level theme (source of truth is the renderer's localStorage)
    theme_custom: dict[str, Any] = field(default_factory=dict)  # backup of custom CSS var overrides (key -> value)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Project":
        def _slot(s: dict[str, Any]) -> SlotRecord:
            known = {f for f in SlotRecord.__dataclass_fields__}
            return SlotRecord(**{k: v for k, v in s.items() if k in known})

        def _stage(s: dict[str, Any]) -> StageRecord:
            slots = [_slot(sl) for sl in s.get("slots", [])]
            known = {f for f in StageRecord.__dataclass_fields__} - {"slots"}
            return StageRecord(**{k: v for k, v in s.items() if k in known}, slots=slots)

        stages = [_stage(s) for s in d.get("stages", [])]
        manual_panes = [
            ManualPaneRecord(**{k: v for k, v in p.items() if k in ManualPaneRecord.__dataclass_fields__})
            for p in d.get("manual_panes", [])
            if isinstance(p, dict)
        ]
        d2 = {**d, "stages": stages, "manual_panes": manual_panes}
        known = {f for f in cls.__dataclass_fields__}
        d2 = {k: v for k, v in d2.items() if k in known}
        return cls(**d2)


class ProjectStore:
    """Manages project.json + pipeline.log under each workspace."""

    def project_dir(self, workspace_path: str) -> Path:
        return Path(workspace_path) / PROJECT_DIR_NAME

    def project_file(self, workspace_path: str) -> Path:
        return self.project_dir(workspace_path) / PROJECT_FILE

    def log_file(self, workspace_path: str, log_file_name: str = "") -> Path:
        """Return the log file path for this workspace.

        If log_file_name is given (from project.log_file_name), use that.
        Falls back to a generic 'pipeline.log' for events outside a run.
        """
        name = log_file_name or "pipeline.log"
        return self.project_dir(workspace_path) / name

    def _ensure_dir(self, workspace_path: str) -> Path:
        d = self.project_dir(workspace_path)
        d.mkdir(parents=True, exist_ok=True)
        # Make the runtime dir self-ignoring so git never tracks it, regardless
        # of the workspace's own .gitignore or staging order. `.gitignore` with
        # `*` ignores the whole directory (including itself) — same pattern as
        # pytest's .pytest_cache/.gitignore.
        gi = d / ".gitignore"
        if not gi.exists():
            gi.write_text("*\n", encoding="utf-8")
        return d

    def peek(self, workspace_path: str) -> Project | None:
        """Return the existing project for this workspace WITHOUT creating one.

        Returns None when:
          - the workspace path is empty / does not exist
          - no .agent-team/project.json is present
          - the JSON file is corrupt (we don't auto-recreate during peek so
            the user isn't surprised by hidden file writes from typing in
            the workspace input)
        """
        if not workspace_path:
            return None
        ws = os.path.abspath(workspace_path)
        if not os.path.isdir(ws):
            return None
        pf = self.project_file(ws)
        if not pf.exists():
            return None
        try:
            data = json.loads(pf.read_text(encoding="utf-8"))
            project = Project.from_dict(data)
            project.workspace_path = ws
            return project
        except Exception as err:  # noqa: BLE001
            log.warning("project.json at %s is corrupt during peek (%s)", pf, err)
            return None

    def load_or_create(
        self, workspace_path: str, *, name: str = "", backend_version: str = ""
    ) -> Project:
        ws = os.path.abspath(workspace_path)
        if not os.path.isdir(ws):
            raise FileNotFoundError(f"workspace does not exist: {ws}")
        pf = self.project_file(ws)
        if pf.exists():
            try:
                data = json.loads(pf.read_text(encoding="utf-8"))
                project = Project.from_dict(data)
                # Keep workspace_path canonical in case the user moved the folder.
                project.workspace_path = ws
                return project
            except Exception as err:  # noqa: BLE001
                log.warning("project.json at %s is corrupt (%s); recreating", pf, err)

        now = _now_iso()
        project = Project(
            id=_project_id_for(ws),
            name=name or Path(ws).name,
            workspace_path=ws,
            created_at=now,
            updated_at=now,
            backend_version=backend_version,
        )
        self.save(project)
        self.append_event(
            ws,
            {
                "event": "project_created",
                "project_id": project.id,
                "name": project.name,
            },
        )
        return project

    def save(self, project: Project) -> Path:
        project.updated_at = _now_iso()
        self._ensure_dir(project.workspace_path)
        pf = self.project_file(project.workspace_path)
        tmp = pf.with_suffix(pf.suffix + ".tmp")
        payload = json.dumps(project.to_dict(), indent=2, ensure_ascii=False)
        tmp.write_text(payload, encoding="utf-8")
        os.replace(tmp, pf)
        return pf

    def append_event(
        self, workspace_path: str, event: dict[str, Any], log_file_name: str = ""
    ) -> Path:
        ws = os.path.abspath(workspace_path)
        self._ensure_dir(ws)
        lf = self.log_file(ws, log_file_name)
        # Auto-create the run sub-folder (e.g. runs/20260528-020041-task/)
        lf.parent.mkdir(parents=True, exist_ok=True)
        line = f"[{_now_iso()}] {json.dumps(event, ensure_ascii=False)}\n"
        with open(lf, "a", encoding="utf-8") as f:
            f.write(line)
        return lf

    # -------- Pipeline-specific high-level ops --------

    def start_pipeline(
        self,
        workspace_path: str,
        *,
        task_description: str,
        total_stages: int,
        stage_blueprint: list[dict[str, Any]],
        backend_version: str = "",
        pipeline_id: str = "",
    ) -> Project:
        project = self.load_or_create(workspace_path, backend_version=backend_version)
        project.task_description = task_description
        project.total_stages = total_stages
        if pipeline_id:
            project.pipeline_id = pipeline_id
        project.state = "running"
        project.current_stage_index = -1  # spawn_stage will bump to 0
        project.stages = [
            StageRecord(
                stage_id=s["stage_id"],
                title=s.get("title", ""),
                slots=[
                    SlotRecord(
                        label=sl.get("label", ""),
                        agent=sl.get("agent", ""),
                        role=sl.get("role", ""),
                    )
                    for sl in s.get("slots", [])
                ],
            )
            for s in stage_blueprint
        ]
        # Each pipeline run gets its own log file.
        project.log_file_name = _make_log_filename(task_description)
        self.save(project)
        self.append_event(
            workspace_path,
            {
                "event": "pipeline_start",
                "project_id": project.id,
                "task": task_description,
                "total_stages": total_stages,
                "log_file": project.log_file_name,
            },
            log_file_name=project.log_file_name,
        )
        return project

    def record_stage_spawn(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        pane_id: str,
        agent: str,
        role: str,
    ) -> Project:
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        # mark previous stage completed (if any) before bumping pointer
        if 0 <= project.current_stage_index < len(project.stages):
            prev = project.stages[project.current_stage_index]
            if prev.status == "running":
                prev.status = "completed"
                prev.ended_at = _now_iso()
        stage = project.stages[stage_index]
        stage.status = "running"
        stage.started_at = _now_iso()
        stage.pane_id = pane_id
        if agent:
            stage.agent = agent
        if role:
            stage.role = role
        project.current_stage_index = stage_index
        project.agents_spawned += 1
        self.save(project)
        self.append_event(
            workspace_path,
            {
                "event": "stage_spawn",
                "stage_index": stage_index,
                "stage_id": stage.stage_id,
                "agent": stage.agent,
                "role": stage.role,
                "pane_id": pane_id,
            },
            log_file_name=project.log_file_name,
        )
        return project

    def record_slot_spawn(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        slot_label: str,
        pane_id: str,
        agent: str = "",
        role: str = "",
        session_id: str = "",
    ) -> Project:
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        stage = project.stages[stage_index]
        slot = next((s for s in stage.slots if s.label == slot_label), None)
        if slot is None:
            slot = SlotRecord(label=slot_label, agent=agent, role=role)
            stage.slots.append(slot)
        slot.pane_id = pane_id
        slot.spawn_status = "spawned"
        if agent:
            slot.agent = agent
        if role:
            slot.role = role
        # Claude pins its session id at spawn, so persist it now; Codex/Gemini
        # pass "" here and get record_slot_session() later once detected.
        if session_id:
            slot.session_id = session_id
        self.save(project)
        return project

    def record_slot_session(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        slot_label: str,
        session_id: str,
    ) -> Project:
        """Persist the CLI session id for a slot so it can be resumed on
        restart. Called later than record_slot_spawn because Codex/Gemini
        ids are only known once the CLI has written its session file."""
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        stage = project.stages[stage_index]
        slot = next((s for s in stage.slots if s.label == slot_label), None)
        if slot is None:
            return project
        slot.session_id = session_id
        self.save(project)
        return project

    def record_slot_unspawn(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        slot_label: str,
    ) -> Project:
        """Mark a pipeline slot as manually removed so it is not auto-restored.

        The session_id is intentionally preserved. If the slot is spawned again
        later, record_slot_spawn can reuse/update it as appropriate.
        """
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        stage = project.stages[stage_index]
        slot = next((s for s in stage.slots if s.label == slot_label), None)
        if slot is None:
            return project
        slot.pane_id = None
        slot.spawn_status = "removed"
        slot.kickoff_status = "none"
        self.save(project)
        self.append_event(
            workspace_path,
            {
                "event": "slot_unspawn",
                "stage_index": stage_index,
                "stage_id": stage.stage_id,
                "slot_label": slot_label,
            },
            log_file_name=project.log_file_name,
        )
        return project

    def record_manual_pane_spawn(
        self,
        workspace_path: str,
        *,
        pane_id: str,
        previous_pane_id: str = "",
        agent: str = "",
        role: str = "",
        command: str = "",
        session_id: str = "",
    ) -> Project:
        project = self.load_or_create(workspace_path)
        pane = next(
            (
                p for p in project.manual_panes
                if p.pane_id == pane_id or (previous_pane_id and p.pane_id == previous_pane_id)
            ),
            None,
        )
        if pane is None:
            pane = ManualPaneRecord(pane_id=pane_id)
            project.manual_panes.append(pane)
        pane.pane_id = pane_id
        pane.agent = agent
        pane.role = role
        pane.command = command
        pane.spawn_status = "spawned"
        if session_id:
            pane.session_id = session_id
        self.save(project)
        self.append_event(
            workspace_path,
            {
                "event": "manual_pane_spawn",
                "pane_id": pane_id,
                "agent": agent,
                "role": role,
            },
            log_file_name=project.log_file_name,
        )
        return project

    def record_manual_pane_unspawn(
        self,
        workspace_path: str,
        *,
        pane_id: str,
    ) -> Project:
        project = self.load_or_create(workspace_path)
        pane = next((p for p in project.manual_panes if p.pane_id == pane_id), None)
        if pane is None:
            return project
        pane.spawn_status = "removed"
        self.save(project)
        self.append_event(
            workspace_path,
            {"event": "manual_pane_unspawn", "pane_id": pane_id},
            log_file_name=project.log_file_name,
        )
        return project

    def record_manual_pane_session(
        self,
        workspace_path: str,
        *,
        pane_id: str,
        session_id: str,
    ) -> Project:
        project = self.load_or_create(workspace_path)
        pane = next((p for p in project.manual_panes if p.pane_id == pane_id), None)
        if pane is None:
            return project
        pane.session_id = session_id
        self.save(project)
        return project

    def record_slot_tmux_name(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        slot_label: str,
        tmux_name: str,
    ) -> Project:
        if tmux_name and not _TMUX_NAME_RE.fullmatch(tmux_name):
            raise ValueError(f"invalid tmux_name: {tmux_name!r}")
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        stage = project.stages[stage_index]
        slot = next((s for s in stage.slots if s.label == slot_label), None)
        if slot is None:
            return project
        slot.tmux_name = tmux_name
        self.save(project)
        return project

    def record_manual_pane_tmux_name(
        self,
        workspace_path: str,
        *,
        pane_id: str,
        tmux_name: str,
    ) -> Project:
        if tmux_name and not _TMUX_NAME_RE.fullmatch(tmux_name):
            raise ValueError(f"invalid tmux_name: {tmux_name!r}")
        project = self.load_or_create(workspace_path)
        pane = next((p for p in project.manual_panes if p.pane_id == pane_id), None)
        if pane is None:
            return project
        pane.tmux_name = tmux_name
        self.save(project)
        return project

    def clear_tmux_name_by_value(self, workspace_path: str, tmux_name: str) -> None:
        """Kill 後清零 project.json 中對應的 tmux_name（避免 stale 記錄）。"""
        if not tmux_name:
            return
        project = self.peek(workspace_path)
        if not project:
            return
        changed = False
        for pane in project.manual_panes:
            if pane.tmux_name == tmux_name:
                pane.tmux_name = ""
                changed = True
        for stage in project.stages:
            for slot in stage.slots:
                if slot.tmux_name == tmux_name:
                    slot.tmux_name = ""
                    changed = True
        if changed:
            self.save(project)

    def update_slot_kickoff(
        self,
        workspace_path: str,
        *,
        stage_index: int,
        slot_label: str,
        kickoff_status: str,
    ) -> Project:
        project = self.load_or_create(workspace_path)
        if stage_index < 0 or stage_index >= len(project.stages):
            raise IndexError(f"stage_index {stage_index} out of range")
        stage = project.stages[stage_index]
        slot = next((s for s in stage.slots if s.label == slot_label), None)
        if slot:
            slot.kickoff_status = kickoff_status
            self.save(project)
        return project

    def resume_pipeline(self, workspace_path: str) -> tuple[Project, int]:
        """Mark an existing pipeline as running again. Returns (project, next_stage_index).

        next_stage_index = -1 means "all stages already completed".
        Picks the first stage whose status is not 'completed'.
        """
        project = self.load_or_create(workspace_path)
        if not project.stages:
            raise ValueError("no pipeline to resume — start one first")

        next_idx = -1
        for i, s in enumerate(project.stages):
            if s.status != "completed":
                next_idx = i
                break

        if next_idx == -1:
            project.state = "completed"
        else:
            project.state = "running"
            project.current_stage_index = next_idx
            # Reset that stage's bookkeeping so a fresh pane records cleanly.
            stage = project.stages[next_idx]
            stage.status = "running"
            stage.started_at = _now_iso()
            stage.ended_at = None
            stage.pane_id = None

        self.save(project)
        self.append_event(
            workspace_path,
            {
                "event": "pipeline_resume",
                "project_id": project.id,
                "resume_index": next_idx,
                "total_stages": project.total_stages,
            },
            log_file_name=project.log_file_name,
        )
        return project, next_idx

    def complete_pipeline(self, workspace_path: str) -> Project:
        project = self.load_or_create(workspace_path)
        # Close any still-running stage
        if 0 <= project.current_stage_index < len(project.stages):
            cur = project.stages[project.current_stage_index]
            if cur.status == "running":
                cur.status = "completed"
                cur.ended_at = _now_iso()
        project.state = "completed"
        project.run_count += 1
        self.save(project)
        self.append_event(
            workspace_path,
            {"event": "pipeline_complete", "project_id": project.id, "run_count": project.run_count},
            log_file_name=project.log_file_name,
        )
        return project

    def abort_pipeline(self, workspace_path: str, *, reason: str = "user") -> Project:
        project = self.load_or_create(workspace_path)
        if 0 <= project.current_stage_index < len(project.stages):
            cur = project.stages[project.current_stage_index]
            if cur.status == "running":
                cur.status = "aborted"
                cur.ended_at = _now_iso()
        project.state = "aborted"
        self.save(project)
        self.append_event(
            workspace_path,
            {"event": "pipeline_abort", "reason": reason, "project_id": project.id},
            log_file_name=project.log_file_name,
        )
        return project

    def record_pane_event(
        self,
        workspace_path: str,
        *,
        event_type: str,
        pane_id: str,
        agent: str = "",
        role: str = "",
        origin: str = "manual",
        details: dict[str, Any] | None = None,
        log_file_name: str = "",
    ) -> None:
        """Lightweight event-only log entry (no project.json update)."""
        body: dict[str, Any] = {
            "event": event_type,
            "pane_id": pane_id,
            "agent": agent,
            "role": role,
            "origin": origin,
        }
        if details:
            body["details"] = details
        self.append_event(workspace_path, body, log_file_name=log_file_name)
